#!/bin/sh
set -e

if [ "$#" -ne 1 ] || (echo "$1" | grep -qv '^[1-9][0-9]*[smhd]\?$'); then
  echo "Usage: pausehostsfilesonly TIME" >&2
  exit 1
fi

"$(dirname "$0")/hostsfilesonly" 0
echo "Waiting..." >&2
sleep "$1"
"$(dirname "$0")/hostsfilesonly" 1

killall firefox
